# Generated by Django 3.2.9 on 2021-11-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localizer', '0004_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Point',
        ),
    ]
