# Generated by Django 3.2.9 on 2021-11-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localizer', '0006_auto_20211105_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Point',
            new_name='Marker',
        ),
    ]
